### ISSUE TITLE
suggest

### ISSUE THREAD

**Issue by NakiriFox** [Test-Account666/LethalCompany-DoorBreach#1]
Thank you very much for creating this mod, as another DoorReach mod has serious bugs👇
https://github.com/Nyxchrono/LC.DoorBreach/issues/7

Perhaps you can tell people this in your mod's introduction page?

**Comment by Test-Account666** [comment]
Tell people about the other mod?

Or do you mean credit the original?

**Comment by NakiriFox** [comment]
Tell people that another mod has serious errors.

**Comment by Test-Account666** [comment]
The mod is outdated and contains bugs.
People know that already...

I don't think it's fair to bash the original mod just because I made a new version.

I'm happy to credit it, if the original creator (Or users of my mod) wish me to do so though :)

Glad you enjoy my mod though ^^
If there are any suggestions you have for it, or my other mods, I'd love to hear about them!

**Comment by NakiriFox** [comment]
Thank you for your reply.
I understand :)
